name = "grantbite"
account_id = "7b74bc49f0de35a5cea10ecc737c5955"
main = "./.cloudflare/worker.js"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"

[assets]
directory = "./static/"
binding = "ASSETS"
