// enums autogenerated from python via https://enum-converter.vercel.app/

export enum FinancialInstrumentType {
  Grant = "Grant",
  Repayable = "Repayable",
  Loan = "Loan",
  Convertible = "Convertible",
  Equity = "Equity",
  Hybrid = "Hybrid",
  Guarantee = "Guarantee",
  Incentive = "Incentive",
  Prize = "Prize",
  Other = "Other",
}

export enum ProgramStatus {
  Planned = "Planned",
  Open = "Open",
  Closed = "Closed",
  Cancelled = "Cancelled",
  Other = "Other",
}

export enum EligibleApplicantsShort {
  IndividualsandEntrepreneurs = "IndividualsandEntrepreneurs",
  Partnerships = "Partnerships",
  Businesses = "Businesses",
  NonProfit = "NonProfit",
  PublicSectorEntities = "PublicSectorEntities",
  EducationalandResearch = "EducationalandResearch",
  Others = "Others",
}

export enum CompanySize {
  lt10 = "lt10",
  lt50 = "lt50",
  lt250 = "lt250",
  lt1000 = "lt1000",
  gt1000 = "gt1000",
}

export enum EligibleSectorsShort {
  AgricultureAndAgribusiness = "AgricultureAndAgribusiness",
  FoodProcessing = "FoodProcessing",
  TextileAndApparelIndustry = "TextileAndApparelIndustry",
  ConstructionAndBuildingMaterials = "ConstructionAndBuildingMaterials",
  PaperAndPackagingIndustry = "PaperAndPackagingIndustry",
  EnergyProductionAndSupply = "EnergyProductionAndSupply",
  RenewableEnergy = "RenewableEnergy",
  WaterAndWasteManagement = "WaterAndWasteManagement",
  TransportationAndLogistics = "TransportationAndLogistics",
  InformationAndCommunicationTechnology = "InformationAndCommunicationTechnology",
  SoftwareDevelopment = "SoftwareDevelopment",
  FinancialTechnology = "FinancialTechnology",
  GreenTechnology = "GreenTechnology",
  Healthcare = "Healthcare",
  MedicalTechnology = "MedicalTechnology",
  PharmaceuticalIndustry = "PharmaceuticalIndustry",
  EducationAndVocationalTraining = "EducationAndVocationalTraining",
  ResearchAndDevelopment = "ResearchAndDevelopment",
  ConsumerGoodsIndustry = "ConsumerGoodsIndustry",
  ServiceSector = "ServiceSector",
  Tourism = "Tourism",
  CreativeIndustries = "CreativeIndustries",
  EnvironmentalAndClimateProtection = "EnvironmentalAndClimateProtection",
  SocialEnterprises = "SocialEnterprises",
  CulturalInstitutions = "CulturalInstitutions",
  Other = "Other",
}

export enum TargetStageShort {
  BasicResearch = "BasicResearch",
  AppliedResearch = "AppliedResearch",
  ExperimentalDevelopment = "ExperimentalDevelopment",
  FeasibilityStudy = "FeasibilityStudy",
  Prototyping = "Prototyping",
  PilotTesting = "PilotTesting",
  ProductDevelopment = "ProductDevelopment",
  ProcessOptimization = "ProcessOptimization",
  MarketIntroduction = "MarketIntroduction",
  Scaling = "Scaling",
  Commercialization = "Commercialization",
  Planning = "Planning",
  PolicyDevelopment = "PolicyDevelopment",
  Implementation = "Implementation",
  Infrastructure = "Infrastructure",
  ServiceDelivery = "ServiceDelivery",
  CapacityBuilding = "CapacityBuilding",
  AwarenessCampaigns = "AwarenessCampaigns",
  Monitoring = "Monitoring",
  Evaluation = "Evaluation",
  Other = "Other",
}

export enum Country {
  Austria = "Austria",
  Belgium = "Belgium",
  Bulgaria = "Bulgaria",
  Croatia = "Croatia",
  Cyprus = "Cyprus",
  Czechia = "Czechia",
  Denmark = "Denmark",
  Estonia = "Estonia",
  Finland = "Finland",
  France = "France",
  Germany = "Germany",
  Greece = "Greece",
  Hungary = "Hungary",
  Ireland = "Ireland",
  Italy = "Italy",
  Latvia = "Latvia",
  Lithuania = "Lithuania",
  Luxembourg = "Luxembourg",
  Malta = "Malta",
  Netherlands = "Netherlands",
  Poland = "Poland",
  Portugal = "Portugal",
  Romania = "Romania",
  Slovakia = "Slovakia",
  Slovenia = "Slovenia",
  Spain = "Spain",
  Sweden = "Sweden",
  Switzerland = "Switzerland",
  UnitedKingdom = "UnitedKingdom",
  Other = "Other",
}

export enum ProgramLevel {
  EuropeanUnion = "EuropeanUnion",
  MultiCountry = "MultiCountry",
  National = "National",
  Regional = "Regional",
  Local = "Local",
  Other = "Other",
  Unknown = "Unknown",
}

export enum AwardChannel {
  IndividualAid = "IndividualAid",
  FrameworkProgrammeCall = "FrameworkProgrammeCall",
  CompetitiveTender = "CompetitiveTender",
  DemandDrivenScheme = "DemandDrivenScheme",
  CascadeFunding = "CascadeFunding",
  SharedManagementSubsidies = "SharedManagementSubsidies",
  IndirectManagementFunding = "IndirectManagementFunding",
  FinancialInstruments = "FinancialInstruments",
  PrizesAndCompetitions = "PrizesAndCompetitions",
  Unknown = "Unknown",
}

export enum SingleConsortium {
  SingleApplicant = "SingleApplicant",
  ConsortiumRequired = "ConsortiumRequired",
  OptionalConsortium = "OptionalConsortium",
  Unknown = "Unknown",
}

export enum Language {
  en = "en",
  de = "de",
  es = "es",
  fr = "fr",
  pt = "pt",
}

export const enums = {
  FinancialInstrumentType,
  ProgramStatus,
  EligibleApplicantsShort,
  CompanySize,
  EligibleSectorsShort,
  TargetStageShort,
  Country,
  ProgramLevel,
  AwardChannel,
  SingleConsortium,
  Language,
}
