<script lang="ts">
  import type { PageData } from "./$types" // Will be generated by SvelteKit
  import { Loader2 } from "lucide-svelte"
  import { navigating } from "$app/stores" // Reverted to $app/stores
  import { goto } from "$app/navigation"
  import { onMount, tick } from "svelte"
  import NewFilterBar from "$lib/components/NewFilterBar.svelte"
  import SearchResultCard from "$lib/components/SearchResultCard.svelte"
  import Button from "$lib/components/ui/button/button.svelte"
  import { m } from "$lib/paraglide/messages"
  import { localizeHref } from "$lib/paraglide/runtime"
  import { page } from "$app/state"
  import { useTextAnimation } from "$src/lib/hooks/use-text-animation"
  import TabsHeader from "$src/lib/components/funding-page-comps/tabs-header.svelte"
  import { IsMobile } from "$src/lib/hooks/is-mobile.svelte"
  let { data } = $props() as { data: PageData }

  const currentUrl = $derived(page.url.href)
  let totalItems = $state(data.totalItems || 0)
  let totalPages = $derived(
    data.itemsPerPage > 0 ? Math.ceil(totalItems / data.itemsPerPage) : 1,
  )
  let searchQuery = $state(data.searchQuery || "")
  let activeFilters = $state(data.activeFilters || {})

  let loadedItems = $state(data.items || [])
  let currentPage = $state(data.currentPage || 1)
  let loading = $state(false)

  $effect(() => {
    searchQuery = data.searchQuery || ""
    activeFilters = data.activeFilters || {}
    loadedItems = data.items || []
    currentPage = data.currentPage || 1
  })

  // Helper function to build URL with filters
  function buildUrlWithFilters(page: number): string {
    // Create a URL path with query parameters
    let url = localizeHref("/funding?page=" + page)

    if (searchQuery) {
      url += "&q=" + encodeURIComponent(searchQuery.trim())
    }

    for (const [key, value] of Object.entries(activeFilters)) {
      const valueArray = Array.isArray(value) ? value : [value]
      for (const item of valueArray) {
        url += `&${encodeURIComponent(key)}=${encodeURIComponent(String(item))}`
      }
    }

    return url
  }
  function storeCurrentUrl() {
    const fullUrl = buildUrlWithFilters(currentPage)
    localStorage.setItem("lastSearchUrl", fullUrl)
  }
  function handleSearch() {
    goto(buildUrlWithFilters(1))
    storeCurrentUrl()
  }

  // Handle filter changes
  async function handleFilterChange(
    filters: Record<string, string | string[]>,
  ) {
    activeFilters = filters

    await tick()
    // Navigate to the new URL with page 1
    goto(buildUrlWithFilters(1), { replaceState: true, keepFocus: true })
    storeCurrentUrl()
  }

  async function loadMorePrograms() {
    if (loading || currentPage >= totalPages) return

    loading = true
    const nextPage = currentPage + 1

    try {
      const newItems = await fetchItems(nextPage)

      // Update state with new data
      loadedItems = [...loadedItems, ...newItems]
      currentPage = nextPage
    } catch (error) {
      console.error("Error loading more programs:", error)
    } finally {
      loading = false
    }
  }

  async function fetchItems(page: number) {
    const params = new URLSearchParams()
    params.append("page", page.toString())

    if (searchQuery) {
      params.append("q", searchQuery)
    }

    for (const [key, value] of Object.entries(activeFilters)) {
      const valueArray = Array.isArray(value) ? value : [value]
      for (const item of valueArray) {
        params.append(key, String(item))
      }
    }

    const response = await fetch(`/api/funding-programs?${params.toString()}`)

    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`)
    }

    const responseData = await response.json()
    return responseData.items || []
  }

  let activeTab = $state("search")

  function handleScroll() {
    if (activeTab !== "search") return

    const bottom =
      window.innerHeight + window.scrollY >=
      document.documentElement.scrollHeight - 100

    if (bottom && !loading && currentPage < totalPages) {
      loadMorePrograms()
    }
  }

  // Initialize the scroll listener
  onMount(() => {
    window.addEventListener("scroll", handleScroll)
    return () => {
      window.removeEventListener("scroll", handleScroll)
    }
  })

  const placeholders = [
    m.hero_program_1(),
    m.hero_program_2(),
    m.hero_program_3(),
    m.hero_program_4(),
  ]

  const getIsMobile = new IsMobile()
  let isMobile = $derived(getIsMobile.current)

  const { currentText } = useTextAnimation(placeholders, 2000)

  // Create a reactive placeholder that updates based on mobile state and current text
  let placeholder = $derived(
    isMobile
      ? $currentText
      : `${m.searchbar_placeholder_text()}: ${$currentText}`,
  )
</script>

<svelte:head>
  <title>
    {data.searchQuery
      ? m.searchpage_title_results({ search: data.searchQuery })
      : m.searchpage_title_search_not_started_yet()} - FundingFinder
  </title>
  <meta name="description" content={m.searchpage_meta_content()} />
  <link rel="canonical" href={currentUrl} />
</svelte:head>

<div class="font-exobg-white flex flex-col">
  <TabsHeader />
  <!-- programs section -->
  <div class="gap-1 relative overflow-hidden min-h-screen">
    <!-- Serach filters -->
    <div
      class="mb-0 p-8 funding-search-bg"
      style="position: relative; z-index: 1;"
    >
      <div
        class="max-w-7xl mx-auto relative space-y-10 flex flex-col lg:items-center py-6 md:py-14"
      >
        <div class="flex flex-col max-w-5xl w-full">
          <!-- Hidden inputs for active filters - all filter values are treated as arrays -->
          {#each Object.entries(activeFilters) as [key, value]}
            {#each Array.isArray(value) ? value : [value] as item}{/each}
          {/each}
          <div class="relative w-full">
            <div
              class="flex items-center relative rounded-md sm:rounded-[20px] h-12 sm:h-20"
            >
              <!-- Monkey Icon -->
              <img
                src="/images/monkey_search.svg"
                alt="Search"
                class="absolute top-1/2 transform -translate-y-1/2 left-3 md:left-5 size-8 sm:size-[50px]"
              />

              <!-- Search Input -->
              <input
                type="search"
                name="q"
                bind:value={searchQuery}
                {placeholder}
                class="w-full h-full bg-white px-12 xs:px-14 md:px-20 text-base font-medium font-exo rounded-md sm:rounded-[20px] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-rin border-2 sm:border-[3px] border-brand-primary"
                onkeypress={(e) => e.key === "Enter" && handleSearch()}
              />

              <!-- Search Button -->
              <Button
                type="button"
                size="icon"
                class="group absolute right-[9px] top-1/2 transform -translate-y-1/2 size-8 sm:size-16 rounded-sm sm:rounded-[10px] flex items-center justify-center"
                onclick={handleSearch}
              >
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke-width="2.5"
                  stroke="white"
                  class="size-6"
                >
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    d="M13.5 4.5 21 12m0 0-7.5 7.5M21 12H3"
                  ></path>
                </svg>
              </Button>
            </div>
          </div>
        </div>
        <!-- Filters Area -->
        <!-- <FilterBar {activeFilters} onChange={handleFilterChange} /> -->
        <NewFilterBar {activeFilters} onChange={handleFilterChange} />
      </div>
    </div>

    <section class="relative">
      <!-- grid lines -->
      <div
        class=" absolute top-[-11rem] w-full h-[800px] z-0 pointer-none hidden md:block bg-[url('/grid-lines-frames.png')] bg-center"
      >
        <div
          class="absolute bottom-0 left-0 w-full pointer-events-none h-3/12"
          style="background: linear-gradient(to bottom, rgba(255, 255, 255, 0) 0%, rgba(255, 255, 255, 1) 120%);"
        ></div>
      </div>
      <!-- Results List -->
      <div
        class="max-w-5xl mx-auto px-6 py-8 w-full flex-grow flex flex-col space-y-6 relative"
      >
        <!-- Results Count -->
        {#if data.totalItems > 0}
          <h2 class="text-2xl font-bold text-gray-800">
            {data.totalItems}
            {m.searchresult_matches_text({ count: data.totalItems })}
            {#if data.searchQuery}
              {m.search_result_for()} "{data.searchQuery}"{/if}
          </h2>
        {/if}
        {#if $navigating}
          <div
            class="flex flex-col items-center justify-center text-center py-12 px-6 min-h-[300px]"
          >
            <Loader2 class="w-12 h-12 text-teal-600 animate-spin mb-4" />
            <p class="text-lg font-medium text-gray-700">{m.loading()}</p>
          </div>
        {:else if loadedItems && loadedItems.length > 0}
          {#each loadedItems as item (item.permalink)}
            <SearchResultCard {item} />
          {/each}

          <!-- Loading indicator for infinite scroll -->
          {#if loading}
            <div class="flex justify-center py-8">
              <Loader2 class="w-8 h-8 text-teal-600 animate-spin" />
            </div>
          {/if}

          <!-- End of results indicator -->
          {#if currentPage >= totalPages && loadedItems.length > 0}
            <div class="text-center py-8">
              <p class="text-gray-500">{m.no_programs()}</p>
            </div>
          {/if}
        {:else if data.totalItems === 0}
          <div class="text-center py-12 px-6 m-auto">
            <div class="flex items-center justify-center">
              <img
                src="/images/monkey_not_found.svg"
                alt="Search"
                class="w-[70px] h-[70px]"
              />
            </div>
            <h3 class="mt-2 text-lg font-medium text-gray-400">
              {m.searchpage_no_search_results()}
            </h3>
          </div>
        {/if}
      </div>
    </section>

    <!-- Pagination - kept commented as you had it -->
    <!-- {#if totalPages > 1}
        <div class=" border-t border-gray-200">
          <div
            class="max-w-5xl mx-auto px-6 mt-4 flex items-center justify-between"
          >
            <div class="-mt-px flex w-0 flex-1">
              {#if data.currentPage > 1}
                <a
                  href={buildUrlWithFilters(data.currentPage - 1)}
                  class="group inline-flex items-center pr-1 pt-4 text-sm font-medium text-gray-500 hover:text-brand-primary"
                >
                  <ArrowLeft
                    class="mr-3 h-5 w-5 text-gray-400 group-hover:text-brand-primary"
                  />
                  {m.searchpage_previous_page()}
                </a>
              {:else}
                <span
                  class="inline-flex items-center border-t-2 border-transparent pr-1 pt-4 text-sm font-medium text-gray-400 cursor-not-allowed"
                >
                  <ArrowLeft class="mr-3 h-5 w-5 text-gray-300" />
                  {m.searchpage_previous_page()}
                </span>
              {/if}
            </div>
            <div class="hidden md:-mt-px md:flex">
              <span
                class="inline-flex items-center border-t-2 border-transparent px-4 pt-4 text-sm font-medium text-gray-500"
              >
                {m.searchpage_page_indicator({
                  current: data.currentPage,
                  total: totalPages,
                })}
              </span>
            </div>
            <div class="-mt-px flex w-0 flex-1 justify-end">
              {#if data.currentPage < totalPages}
                <a
                  href={buildUrlWithFilters(data.currentPage + 1)}
                  class="group inline-flex items-center pl-1 pt-4 text-sm font-medium text-gray-500 hover:text-brand-primary"
                >
                  {m.searchpage_next_page()}
                  <ArrowRight
                    class="ml-3 h-5 w-5 text-gray-400 group-hover:text-brand-primary"
                  />
                </a>
              {:else}
                <span
                  class="inline-flex items-center pl-1 pt-4 text-sm font-medium text-gray-400 cursor-not-allowed"
                >
                  {m.searchpage_next_page()}
                  <ArrowRight class="ml-3 h-5 w-5 text-gray-300" />
                </span>
              {/if}
            </div>
          </div>
        </div>
      {/if} -->
  </div>
</div>

<style>
  /* Additional specific styles can go here if Tailwind isn't sufficient */
  /* For example, to ensure the search input border is exactly 3px */
  input[type="search"] {
    border-width: 3px;
  }

  /* Make the search bar responsive */
  @media (max-width: 768px) {
    input[type="search"] {
      font-size: 14px;
    }
  }

  @media (max-width: 480px) {
    input[type="search"]::placeholder {
      font-size: 12px;
    }
  }
</style>
