<script lang="ts">
  import type { PageData } from "./$types" // Will be generated by SvelteKit
  import { ArrowLeft, ArrowRight, Bookmark, Loader2 } from "lucide-svelte"
  import { navigating } from "$app/stores" // Reverted to $app/stores
  import { goto } from "$app/navigation"
  import { tick } from "svelte"
  import SearchResultCard from "$lib/components/SearchResultCard.svelte"
  import { m } from "$src/lib/paraglide/messages"

  let { data } = $props() as { data: PageData }

  let totalPages = $derived(
    data.itemsPerPage > 0 ? Math.ceil(data.totalItems / data.itemsPerPage) : 1,
  )
  let searchQuery = $state(data.searchQuery || "")
  let activeFilters = $state(data.activeFilters || {})

  // Reactive statement to update searchQuery when data.searchQuery changes (e.g. back/forward navigation)
  $effect(() => {
    searchQuery = data.searchQuery || ""
    activeFilters = data.activeFilters || {}
  })

  // Helper function to build URL with filters
  function buildUrlWithFilters(page: number): string {
    // Create a URL path with query parameters
    let url = "/funding?page=" + page

    // Add search query if present
    if (data.searchQuery) {
      url += "&q=" + encodeURIComponent(data.searchQuery)
    }

    // Add filters - all filter values are treated as arrays
    for (const [key, value] of Object.entries(activeFilters)) {
      const valueArray = Array.isArray(value) ? value : [value]
      for (const item of valueArray) {
        url += `&${encodeURIComponent(key)}=${encodeURIComponent(String(item))}`
      }
    }

    return url
  }

  // Handle filter changes
  async function handleFilterChange(
    filters: Record<string, string | string[]>,
  ) {
    activeFilters = filters

    await tick()
    // Navigate to the new URL with page 1
    goto(buildUrlWithFilters(1), { replaceState: true, keepFocus: true })
  }
</script>

<svelte:head>
  <title>
    {data.searchQuery ? `Results for "${data.searchQuery}"` : "Funding Search"} -
    FundingFinder
  </title>
  <meta
    name="description"
    content="Search for funding programs on FundingFinder."
  />
</svelte:head>

<div class="font-exo pb-8 min-h-screen app-container flex flex-col">
  <!-- Results List -->
  <div class="flex items-center mt-11 gap-5 pb-6 border-b-2">
    <Bookmark class="size-12 fill-teal-600 text-teal-600" />
    <h1 class="font-bold text-2xl md:text-4xl">{m.navbar_bookmarks()}</h1>
  </div>
  <div
    class="space-y-6 max-w-5xl mx-auto px-6 py-8 grow flex flex-col items-center"
  >
    <!-- Results Count -->
    <!-- {#if data.totalItems > 0}
      <h2 class="text-2xl font-bold text-gray-800 mb-6">
        {data.totalItems} Match{#if data.totalItems !== 1}es{/if}
        {#if data.searchQuery}
          for "{data.searchQuery}"{/if}
      </h2>
    {/if} -->
    {#if $navigating}
      <div
        class="flex flex-col items-center justify-center text-center py-12 px-6 min-h-[300px]"
      >
        <Loader2 class="w-12 h-12 text-teal-600 animate-spin mb-4" />
        <!-- <p class="text-lg font-medium text-gray-700">Loading results...</p> -->
      </div>
    {:else if data.items && data.items.length > 0}
      {#each data.items as item (item.permalink)}
        <SearchResultCard {item} />
      {/each}
    {:else if data.totalItems === 0}
      <div class="text-center py-12 px-6 my-auto">
        <div class="flex items-center justify-center">
          <img
            src="/images/empty-monkey-placeholder.png"
            alt="monkey with bell"
            class="sm:size-20 size-16"
          />
        </div>
        <p class="mt-2 text-lg font-medium text-gray-500">
          {m.no_bookmark_msg()}
        </p>
      </div>
    {/if}
  </div>

  <!-- Pagination -->
  {#if totalPages > 1}
    <div class=" border-t border-gray-200">
      <div
        class="max-w-5xl mx-auto px-6 mt-4 flex items-center justify-between"
      >
        <div class="-mt-px flex w-0 flex-1">
          {#if data.currentPage > 1}
            <a
              href={buildUrlWithFilters(data.currentPage - 1)}
              class="group inline-flex items-center pr-1 pt-4 text-sm font-medium text-gray-500 hover:text-brand-primary"
            >
              <ArrowLeft
                class="mr-3 h-5 w-5 text-gray-400 group-hover:text-brand-primary"
              />
              Previous
            </a>
          {:else}
            <span
              class="inline-flex items-center border-t-2 border-transparent pr-1 pt-4 text-sm font-medium text-gray-400 cursor-not-allowed"
            >
              <ArrowLeft class="mr-3 h-5 w-5 text-gray-300" />
              Previous
            </span>
          {/if}
        </div>
        <div class="hidden md:-mt-px md:flex">
          <!-- Basic page number display -->
          <span
            class="inline-flex items-center border-t-2 border-transparent px-4 pt-4 text-sm font-medium text-gray-500"
          >
            Page {data.currentPage} of {totalPages}
          </span>
        </div>
        <div class="-mt-px flex w-0 flex-1 justify-end">
          {#if data.currentPage < totalPages}
            <a
              href={buildUrlWithFilters(data.currentPage + 1)}
              class="group inline-flex items-center pl-1 pt-4 text-sm font-medium text-gray-500 hover:text-brand-primary"
            >
              Next
              <ArrowRight
                class="ml-3 h-5 w-5 text-gray-400 group-hover:text-brand-primary"
              />
            </a>
          {:else}
            <span
              class="inline-flex items-center pl-1 pt-4 text-sm font-medium text-gray-400 cursor-not-allowed"
            >
              Next
              <ArrowRight class="ml-3 h-5 w-5 text-gray-300" />
            </span>
          {/if}
        </div>
      </div>
    </div>
  {/if}
</div>
