import { m } from "../paraglide/messages"

export const industries = [
  { value: "technology", label: m.industries_technology() },
  { value: "finance", label: m.industries_finance() },
  { value: "healthcare", label: m.industries_healthcare() },
  { value: "education", label: m.industries_education() },
  { value: "real-estate", label: m.industries_real_estate() },
  { value: "retail", label: m.industries_retail() },
  { value: "manufacturing", label: m.industries_manufacturing() },
  { value: "transportation", label: m.industries_transportation() },
  { value: "construction", label: m.industries_construction() },
  { value: "entertainment", label: m.industries_entertainment() },
  { value: "agriculture", label: m.industries_agriculture() },
  { value: "hospitality", label: m.industries_hospitality() },
  { value: "legal", label: m.industries_legal() },
  { value: "marketing", label: m.industries_marketing() },
  { value: "non_profit", label: m.industries_non_profit() },
]
export const stages = [
  { value: "research-development", label: m.stages_research_development() },
  { value: "prototype-testing", label: m.stages_prototype_testing() },
  { value: "scaling-growth", label: m.stages_scaling_growth() },
]
export const fundingPurpose = [
  { value: "staff-salaries", label: m.funding_staff_salaries() },
  { value: "personal", label: m.funding_personal() },
  { value: "external-services", label: m.funding_external_services() },
  {
    value: "equipment-material-purchases",
    label: m.funding_equipment_material(),
  },
  { value: "other", label: m.funding_other() },
]

export const DemoProjects = [
  {
    id: "ffdcf973-2577-4d51-9e22-de5c48c7142e",
    src_url:
      "https://www.foerderdatenbank.de/FDB/Content/DE/Foerderprogramm/EU/zoll.html",
    updated_at: "2025-06-14T06:51:49.907731+00:00",
    success: true,
    featured_priority: 0,
    overview_financial_instrument: "Grant",
    overview_award_channel: "FrameworkProgrammeCall",
    provider_program_level: "EuropeanUnion",
    program_status: "Open",
    overview_eligible_applicants_short: ["PublicSectorEntities"],
    overview_eligible_sectors_short: ["Other"],
    overview_target_stages_short: [
      "BasicResearch",
      "AppliedResearch",
      "ExperimentalDevelopment",
      "FeasibilityStudy",
      "Prototyping",
      "ProductDevelopment",
      "Planning",
      "Implementation",
      "Infrastructure",
      "CapacityBuilding",
      "AwarenessCampaigns",
    ],
    overview_countries: [
      "Austria",
      "Belgium",
      "Bulgaria",
      "Croatia",
      "Cyprus",
      "Czechia",
      "Denmark",
      "Estonia",
      "Finland",
      "France",
      "Germany",
      "Greece",
      "Hungary",
      "Ireland",
      "Italy",
      "Latvia",
      "Lithuania",
      "Luxembourg",
      "Malta",
      "Netherlands",
      "Poland",
      "Portugal",
      "Romania",
      "Slovakia",
      "Slovenia",
      "Spain",
      "Sweden",
      "Other",
    ],
    overview_single_consortium: "OptionalConsortium",
    overview_company_size: [],
    contact: {
      name: "Bundesministerium der Finanzen (BMF)",
      subtitle: null,
      address: "Wilhelmstraße 97, 10116 Berlin, Deutschland",
      phone: "03018 6820",
      fax: null,
      email: "Poststelle@bmf.bund.de",
      website: {
        url: "https://bundesfinanzministerium.de/Web/DE/Home/home.html",
        name: "Bundesministerium der Finanzen",
      },
    },
    funding_translations: [
      {
        id: "ffdcf973-2577-4d51-9e22-de5c48c7142e",
        title: "Customs – Cooperation in Customs Matters (2021–2027)",
        success: true,
        language: "en",
        permalink: "eu-customs-cooperation-program",
        seo_title: "Secure EU Customs Funding: Boost Cooperation & Union",

        seo_keywords: [
          "EU Customs Program",
          "Customs Union",
          "Customs Cooperation",
          "Customs Authorities",
          "Customs Policy",
          "Customs Law",
          "Customs IT Capacities",
          "European Customs Union",
          "Customs Administrative Capacities",
          "Customs Innovation",
          "Protect Illegal Trade",
          "Strengthen Single Market",
          "EU Financial Interests",
          "European Electronic Systems",
          "Customs Training",
          "Best Practices Customs",
          "Customs Law Application",
          "Customs Administration",
        ],
        overview_region:
          "EU Member States, accession countries, candidate countries, potential candidate countries, European Neighbourhood Policy partner countries",
        overview_deadline: "",
        introduction_short:
          "The European Union's 'Customs' program aims to strengthen cooperation and uniform action within the Customs Union and among customs authorities in the EU. It protects the financial and economic interests of the Union and its Member States, promoting security and facilitating legitimate economic activities.",
        overview_open_until: "31.12.2027",
        provider_managed_by: "European Commission",
        overview_beneficiary:
          "Customs authorities, other bodies in participating countries responsible for customs administration or customs-related activities",
        seo_meta_description:
          "The EU Customs Program strengthens cooperation among customs authorities, safeguarding the single market and fighting illegal trade. Secure up to 100% grants for customs, IT, and innovation. Learn more!",
        provider_funding_body: "European Commission",
        overview_allocated_budget: "EUR 950,000,000 for the period 2021-2027",
        overview_program_acronym_id: "Customs, Regulation (EU) 2021/444",
        provider_additional_partners:
          "Federal Ministry of Finance (BMF) - Coordination in Germany",
        overview_eligible_sectors_long:
          "Customs matters, customs policy, customs law, IT capacities in the customs area, development of administrative capacities and human competencies, innovation in customs policy.",
        overview_maximum_funding_amount: "100% of eligible costs",
        overview_eligible_applicants_long:
          "Customs authorities, other bodies in participating countries responsible for customs administration or customs-related activities. External experts such as representatives of government agencies (including from third countries), academics, representatives of international and other relevant organizations, economic operators, organizations representing economic operators, and civil society may participate and potentially be reimbursed for costs.",
        overview_program_title_without_acronym:
          "Cooperation in Customs Matters",
      },
    ],
    bookmarks: [
      {
        user_id: "d648ea83-543f-41a7-b5cf-3dff73d86a79",
      },
      {
        user_id: "cd3a78d8-b192-4259-8ad3-7c77d71c3b25",
      },
    ],
    title: "Customs – Cooperation in Customs Matters (2021–2027)",
    language: "en",
    permalink: "eu-customs-cooperation-program",
    seo_title: "Secure EU Customs Funding: Boost Cooperation & Union",

    seo_keywords: [
      "EU Customs Program",
      "Customs Union",
      "Customs Cooperation",
      "Customs Authorities",
      "Customs Policy",
      "Customs Law",
      "Customs IT Capacities",
      "European Customs Union",
      "Customs Administrative Capacities",
      "Customs Innovation",
      "Protect Illegal Trade",
      "Strengthen Single Market",
      "EU Financial Interests",
      "European Electronic Systems",
      "Customs Training",
      "Best Practices Customs",
      "Customs Law Application",
      "Customs Administration",
    ],
    overview_region:
      "EU Member States, accession countries, candidate countries, potential candidate countries, European Neighbourhood Policy partner countries",
    overview_deadline: "",
    introduction_short:
      "The European Union's 'Customs' program aims to strengthen cooperation and uniform action within the Customs Union and among customs authorities in the EU. It protects the financial and economic interests of the Union and its Member States, promoting security and facilitating legitimate economic activities.",
    overview_open_until: "31.12.2027",
    provider_managed_by: "European Commission",
    overview_beneficiary:
      "Customs authorities, other bodies in participating countries responsible for customs administration or customs-related activities",
    seo_meta_description:
      "The EU Customs Program strengthens cooperation among customs authorities, safeguarding the single market and fighting illegal trade. Secure up to 100% grants for customs, IT, and innovation. Learn more!",
    provider_funding_body: "European Commission",
    overview_allocated_budget: "EUR 950,000,000 for the period 2021-2027",
    overview_program_acronym_id: "Customs, Regulation (EU) 2021/444",
    provider_additional_partners:
      "Federal Ministry of Finance (BMF) - Coordination in Germany",
    overview_eligible_sectors_long:
      "Customs matters, customs policy, customs law, IT capacities in the customs area, development of administrative capacities and human competencies, innovation in customs policy.",
    overview_maximum_funding_amount: "100% of eligible costs",
    overview_eligible_applicants_long:
      "Customs authorities, other bodies in participating countries responsible for customs administration or customs-related activities. External experts such as representatives of government agencies (including from third countries), academics, representatives of international and other relevant organizations, economic operators, organizations representing economic operators, and civil society may participate and potentially be reimbursed for costs.",
    overview_program_title_without_acronym: "Cooperation in Customs Matters",
    bookmarked: true,
  },
  {
    id: "ffca6c5b-bee7-4067-9e55-01ec74348f06",
    src_url:
      "https://www.foerderdatenbank.de/FDB/Content/DE/Foerderprogramm/Land/Sachsen/buergschaft-sachsen-wirtschaft-freie-berufe.html",
    updated_at: "2025-06-16T09:26:32.844826+00:00",
    success: true,
    featured_priority: 0,
    overview_financial_instrument: "Guarantee",
    overview_award_channel: "DemandDrivenScheme",
    provider_program_level: "Regional",
    program_status: "Open",
    overview_eligible_applicants_short: [
      "Businesses",
      "IndividualsandEntrepreneurs",
    ],
    overview_eligible_sectors_short: ["CreativeIndustries", "Other"],
    overview_target_stages_short: [
      "Implementation",
      "Scaling",
      "Commercialization",
      "Other",
    ],
    overview_countries: ["Germany"],
    overview_single_consortium: "SingleApplicant",
    overview_company_size: [],
    contact: {
      name: "Sächsische Aufbaubank – Förderbank – (SAB)",
      subtitle: null,
      address: "Pirnaische Straße 9, 01069 Dresden",
      phone: "0351 49100",
      fax: "0351 49104000",
      email: "servicecenter@sab.sachsen.de",
      website: {
        url: "https://www.sab.sachsen.de/",
        name: "Sächsische Aufbaubank – Förderbank – (SAB)",
      },
    },
    funding_translations: [
      {
        id: "ffca6c5b-bee7-4067-9e55-01ec74348f06",
        title:
          "Guarantees for Commercial Enterprises and Liberal Professions (State Guarantee Program)",
        success: true,
        language: "en",
        permalink: "guarantees-saxony-state-program",
        seo_title: "Saxony Guarantees: Secure Business Financing & Growth",

        updated_at: "2025-06-16T09:26:32.844826+00:00",
        seo_keywords: [
          "Saxony Guarantees",
          "Business Financing Saxony",
          "Commercial Enterprise Funding",
          "Liberal Professions Guarantee",
          "Investment Guarantee",
          "Working Capital Guarantee",
          "Business Succession",
          "Consolidation Saxony",
          "SAB Guarantee",
          "Saxony State Guarantee Program",
          "Loan Security Saxony",
          "Financing without Collateral",
          "Small Business Funding",
          "Start-ups Saxony",
          "Media Guarantees",
          "EU State Aid Regulation",
          "Saxon State Ministry of Finance",
          "General Block Exemption Regulation",
          "De minimis Aid",
          "Viable Business Concept",
        ],
        overview_region: "Saxony",
        overview_deadline: "always open",
        introduction_short:
          "The Saxony State Guarantee Program supports commercial enterprises and liberal professionals in the Free State with financing investments, working capital, and business successions. It offers default guarantees for loans when traditional collateral is insufficient. This program enables important projects and contributes to strengthening the Saxon economy.",
        overview_open_until: "Ongoing",
        provider_managed_by: "Sächsische Aufbaubank – Förderbank – (SAB)",
        overview_beneficiary: "Commercial enterprises, Liberal professions",
        seo_meta_description:
          "Discover the State Guarantee Program in Saxony for commercial enterprises and liberal professions. Secure your investments, working capital, or business succession with SAB guarantees. Apply for financing in Saxony now!",
        provider_funding_body: "Saxon State Ministry of Finance (SMF)",
        overview_allocated_budget: "",
        overview_program_acronym_id: "Landesbürgschaftsprogramm",
        provider_additional_partners: "Bürgschaftsbank Sachsen GmbH (BBS)",
        overview_eligible_sectors_long:
          "Commercial enterprises, liberal professions, order-related working capital for film and television productions. Excluded are non-profit organizations, municipal enterprises, housing and urban development, primary agricultural and forestry production.",
        overview_maximum_funding_amount: "80% of the guaranteed loan sum",
        overview_eligible_applicants_long:
          "Commercial enterprises (excluding municipal enterprises), other economic entities, liberal professionals, and individuals who wish to participate in a leading position in a company with the help of the guaranteed loan.",
        overview_program_title_without_acronym:
          "Guarantees for Commercial Enterprises and Liberal Professions",
      },
    ],
    bookmarks: [
      {
        user_id: "d648ea83-543f-41a7-b5cf-3dff73d86a79",
      },
      {
        user_id: "cd3a78d8-b192-4259-8ad3-7c77d71c3b25",
      },
    ],
    title:
      "Guarantees for Commercial Enterprises and Liberal Professions (State Guarantee Program)",
    language: "en",
    permalink: "guarantees-saxony-state-program",
    seo_title: "Saxony Guarantees: Secure Business Financing & Growth",

    seo_keywords: [
      "Saxony Guarantees",
      "Business Financing Saxony",
      "Commercial Enterprise Funding",
      "Liberal Professions Guarantee",
      "Investment Guarantee",
      "Working Capital Guarantee",
      "Business Succession",
      "Consolidation Saxony",
      "SAB Guarantee",
      "Saxony State Guarantee Program",
      "Loan Security Saxony",
      "Financing without Collateral",
      "Small Business Funding",
      "Start-ups Saxony",
      "Media Guarantees",
      "EU State Aid Regulation",
      "Saxon State Ministry of Finance",
      "General Block Exemption Regulation",
      "De minimis Aid",
      "Viable Business Concept",
    ],
    overview_region: "Saxony",
    overview_deadline: "always open",
    introduction_short:
      "The Saxony State Guarantee Program supports commercial enterprises and liberal professionals in the Free State with financing investments, working capital, and business successions. It offers default guarantees for loans when traditional collateral is insufficient. This program enables important projects and contributes to strengthening the Saxon economy.",
    overview_open_until: "Ongoing",
    provider_managed_by: "Sächsische Aufbaubank – Förderbank – (SAB)",
    overview_beneficiary: "Commercial enterprises, Liberal professions",
    seo_meta_description:
      "Discover the State Guarantee Program in Saxony for commercial enterprises and liberal professions. Secure your investments, working capital, or business succession with SAB guarantees. Apply for financing in Saxony now!",
    provider_funding_body: "Saxon State Ministry of Finance (SMF)",
    overview_allocated_budget: "",
    overview_program_acronym_id: "Landesbürgschaftsprogramm",
    provider_additional_partners: "Bürgschaftsbank Sachsen GmbH (BBS)",
    overview_eligible_sectors_long:
      "Commercial enterprises, liberal professions, order-related working capital for film and television productions. Excluded are non-profit organizations, municipal enterprises, housing and urban development, primary agricultural and forestry production.",
    overview_maximum_funding_amount: "80% of the guaranteed loan sum",
    overview_eligible_applicants_long:
      "Commercial enterprises (excluding municipal enterprises), other economic entities, liberal professionals, and individuals who wish to participate in a leading position in a company with the help of the guaranteed loan.",
    overview_program_title_without_acronym:
      "Guarantees for Commercial Enterprises and Liberal Professions",
    bookmarked: true,
  },
  {
    id: "ffbe5aa4-04df-4b65-97ca-aaa5cb65fbdf",
    src_url:
      "https://www.foerderdatenbank.de/FDB/Content/DE/Foerderprogramm/Bund/BMWSB/jung-kauft-alt.html",
    updated_at: "2025-06-16T09:26:42.365302+00:00",
    success: true,
    featured_priority: 0,
    overview_financial_instrument: "Loan",
    overview_award_channel: "DemandDrivenScheme",
    provider_program_level: "National",
    program_status: "Open",
    overview_eligible_applicants_short: ["IndividualsandEntrepreneurs"],
    overview_eligible_sectors_short: [
      "EnergyProductionAndSupply",
      "RenewableEnergy",
      "ConstructionAndBuildingMaterials",
    ],
    overview_target_stages_short: ["Implementation"],
    overview_countries: ["Germany"],
    overview_single_consortium: "SingleApplicant",
    overview_company_size: [],
    contact: {
      name: "KfW Bankengruppe",
      subtitle: null,
      address: "Palmengartenstraße 5–9, 60325 Frankfurt am Main",
      phone: "+49 800 539-9001",
      fax: null,
      email: "info@kfw.de",
      website: {
        url: "https://www.kfw.de",
        name: "KfW Bankengruppe",
      },
    },
    funding_translations: [
      {
        id: "ffbe5aa4-04df-4b65-97ca-aaa5cb65fbdf",
        title:
          'Federal Funding for Family Homeownership (Existing Properties) "Young Buys Old"',
        success: true,
        language: "en",
        permalink: "federal-funding-family-homeownership-existing",
        seo_title: "Young Buys Old: Secure Family Homeownership with KfW Loans",

        updated_at: "2025-06-16T09:26:42.365302+00:00",
        seo_keywords: [
          "Homeownership families Germany",
          "Young Buys Old",
          "Existing property funding loan",
          "Property purchase families",
          "KfW homeownership",
          "Existing property acquisition funding",
          "Energy efficiency housing",
          "Housing construction funding",
          "Housing modernization",
          "Private individuals funding",
          "Federal homeownership funding",
          "Family property funding",
          "Purchase old apartment",
          "Renovation loan families",
          "Property acquisition",
        ],
        overview_region: "Germany",
        overview_deadline: "always open",
        introduction_short:
          'The Federal Funding for Family Homeownership "Young Buys Old" supports families nationwide in purchasing existing properties. The program offers loans to finance the acquisition and energy-efficient modernization of existing residential property. It aims to enable families to acquire sustainable and energy-efficient homeownership.',
        overview_open_until: "Ongoing",
        provider_managed_by: "KfW Banking Group",
        overview_beneficiary: "",
        seo_meta_description:
          'Discover the Federal Funding for Family Homeownership "Young Buys Old". Secure attractive KfW loans for purchasing and energy-efficient modernization of existing properties. Learn more now!',
        provider_funding_body:
          "Federal Ministry for Housing, Urban Development and Building (BMWSB)",
        overview_allocated_budget: "",
        overview_program_acronym_id: "308, Jung kauft Alt",
        provider_additional_partners: "",
        overview_eligible_sectors_long:
          "Energy efficiency, Renewable energies, Housing construction, Modernization",
        overview_maximum_funding_amount: "",
        overview_eligible_applicants_long: "Private individuals",
        overview_program_title_without_acronym:
          "Federal Funding for Family Homeownership (Existing Properties)",
      },
    ],
    bookmarks: [],
    title:
      'Federal Funding for Family Homeownership (Existing Properties) "Young Buys Old"',
    language: "en",
    permalink: "federal-funding-family-homeownership-existing",
    seo_title: "Young Buys Old: Secure Family Homeownership with KfW Loans",

    seo_keywords: [
      "Homeownership families Germany",
      "Young Buys Old",
      "Existing property funding loan",
      "Property purchase families",
      "KfW homeownership",
      "Existing property acquisition funding",
      "Energy efficiency housing",
      "Housing construction funding",
      "Housing modernization",
      "Private individuals funding",
      "Federal homeownership funding",
      "Family property funding",
      "Purchase old apartment",
      "Renovation loan families",
      "Property acquisition",
    ],
    overview_region: "Germany",
    overview_deadline: "always open",
    introduction_short:
      'The Federal Funding for Family Homeownership "Young Buys Old" supports families nationwide in purchasing existing properties. The program offers loans to finance the acquisition and energy-efficient modernization of existing residential property. It aims to enable families to acquire sustainable and energy-efficient homeownership.',
    overview_open_until: "Ongoing",
    provider_managed_by: "KfW Banking Group",
    overview_beneficiary: "",
    seo_meta_description:
      'Discover the Federal Funding for Family Homeownership "Young Buys Old". Secure attractive KfW loans for purchasing and energy-efficient modernization of existing properties. Learn more now!',
    provider_funding_body:
      "Federal Ministry for Housing, Urban Development and Building (BMWSB)",
    overview_allocated_budget: "",
    overview_program_acronym_id: "308, Jung kauft Alt",
    provider_additional_partners: "",
    overview_eligible_sectors_long:
      "Energy efficiency, Renewable energies, Housing construction, Modernization",
    overview_maximum_funding_amount: "",
    overview_eligible_applicants_long: "Private individuals",
    overview_program_title_without_acronym:
      "Federal Funding for Family Homeownership (Existing Properties)",
    bookmarked: false,
  },
  {
    id: "ff9038ea-9460-495b-99d0-044328f69109",
    src_url:
      "https://www.foerderdatenbank.de/FDB/Content/DE/Foerderprogramm/Land/Bayern/foerderung-neuer-ambulant-betreuter-wohngemein.html",
    updated_at: "2025-06-16T09:27:29.470844+00:00",
    success: true,
    featured_priority: 0,
    overview_financial_instrument: "Grant",
    overview_award_channel: "DemandDrivenScheme",
    provider_program_level: "Regional",
    program_status: "Open",
    overview_eligible_applicants_short: [
      "NonProfit",
      "Businesses",
      "PublicSectorEntities",
      "EducationalandResearch",
    ],
    overview_eligible_sectors_short: [
      "Healthcare",
      "ServiceSector",
      "ResearchAndDevelopment",
    ],
    overview_target_stages_short: [
      "Implementation",
      "AppliedResearch",
      "ExperimentalDevelopment",
      "Planning",
      "Evaluation",
      "ServiceDelivery",
    ],
    overview_countries: ["Germany"],
    overview_single_consortium: "SingleApplicant",
    overview_company_size: [],
    contact: {
      name: "Bayerisches Landesamt für Pflege (LfP)",
      subtitle: "Referat 44",
      address: "Mildred-Scheel-Straße 4, 92224 Amberg",
      phone: "09621 96692541",
      fax: null,
      email: "poststelle@lfp.bayern.de",
      website: {
        url: "https://www.lfp.bayern.de",
        name: "Bayerisches Landesamt für Pflege (LfP)",
      },
    },
    funding_translations: [
      {
        id: "ff9038ea-9460-495b-99d0-044328f69109",
        title:
          "Funding for New Outpatient-Assisted Shared Living Facilities and Projects to Improve Quality of Life and Framework Conditions in Care (Care Funding Guideline – WoLeRaF)",
        success: true,
        language: "en",
        permalink: "funding-nursing-bavaria-living-communities",
        seo_title:
          "Secure up to 100,000 € for Care Facilities & Short-Term Care in Bavaria!",

        updated_at: "2025-06-16T09:27:29.470844+00:00",
        seo_keywords: [
          "Outpatient-assisted shared living facilities",
          "Care funding Bavaria",
          "Create short-term care places",
          "Support for those in need of care",
          "Quality of life in care",
          "Care innovations Bavaria",
          "New shared living facilities care",
          "Care strengthening act Bavaria",
          "Care for those in need of care",
          "Develop care concepts",
          "Inpatient care facilities",
          "Relieve home care",
          "Scientific support for care",
          "Care public relations",
          "Care funding grant",
          "Bavarian State Office for Nursing",
          "Bavarian Ministry of Health",
          "PfleWoqG Bavaria",
          "Social Code Book XI",
        ],
        overview_region: "Bavaria",
        overview_deadline: "",
        introduction_short:
          "The Free State of Bavaria supports the establishment and expansion of new outpatient-assisted shared living facilities for adults in need of care, as well as the creation of short-term care places, through its Care Funding Guideline (WoLeRaF). Additionally, individual projects aimed at improving the quality of life and framework conditions in care are funded. The program seeks to promote innovative care models and adaptation to demographic changes.",
        overview_open_until: "31.12.2026",
        provider_managed_by:
          "Bavarian State Office for Nursing (LfP), Bavarian State Ministry of Health, Care and Prevention",
        overview_beneficiary: "Persons in need of care, informal caregivers",
        seo_meta_description:
          "Secure up to 100,000 € for outpatient shared living facilities, short-term care, or innovative care quality projects in Bavaria. Enhance life quality. Apply now!",
        provider_funding_body:
          "Bavarian State Ministry of Health, Care and Prevention",
        overview_allocated_budget: "",
        overview_program_acronym_id: "WoLeRaF, 43c-G8300-2022/7768-1",
        provider_additional_partners: "",
        overview_eligible_sectors_long:
          "Care and support, Health, Social services, Research and development in the care sector",
        overview_maximum_funding_amount: "100.000 €",
        overview_eligible_applicants_long:
          "Initiators of new outpatient-assisted shared living facilities in Bavaria, operators of full-time inpatient care facilities, operators of inpatient care facilities, and institutions suitable for scientifically supporting projects to improve framework conditions in care.",
        overview_program_title_without_acronym:
          "Funding for New Outpatient-Assisted Shared Living Facilities and Projects to Improve Quality of Life and Framework Conditions in Care",
      },
    ],
    bookmarks: [],
    title:
      "Funding for New Outpatient-Assisted Shared Living Facilities and Projects to Improve Quality of Life and Framework Conditions in Care (Care Funding Guideline – WoLeRaF)",
    language: "en",
    permalink: "funding-nursing-bavaria-living-communities",
    seo_title:
      "Secure up to 100,000 € for Care Facilities & Short-Term Care in Bavaria!",

    seo_keywords: [
      "Outpatient-assisted shared living facilities",
      "Care funding Bavaria",
      "Create short-term care places",
      "Support for those in need of care",
      "Quality of life in care",
      "Care innovations Bavaria",
      "New shared living facilities care",
      "Care strengthening act Bavaria",
      "Care for those in need of care",
      "Develop care concepts",
      "Inpatient care facilities",
      "Relieve home care",
      "Scientific support for care",
      "Care public relations",
      "Care funding grant",
      "Bavarian State Office for Nursing",
      "Bavarian Ministry of Health",
      "PfleWoqG Bavaria",
      "Social Code Book XI",
    ],
    overview_region: "Bavaria",
    overview_deadline: "",
    introduction_short:
      "The Free State of Bavaria supports the establishment and expansion of new outpatient-assisted shared living facilities for adults in need of care, as well as the creation of short-term care places, through its Care Funding Guideline (WoLeRaF). Additionally, individual projects aimed at improving the quality of life and framework conditions in care are funded. The program seeks to promote innovative care models and adaptation to demographic changes.",
    overview_open_until: "31.12.2026",
    provider_managed_by:
      "Bavarian State Office for Nursing (LfP), Bavarian State Ministry of Health, Care and Prevention",
    overview_beneficiary: "Persons in need of care, informal caregivers",
    seo_meta_description:
      "Secure up to 100,000 € for outpatient shared living facilities, short-term care, or innovative care quality projects in Bavaria. Enhance life quality. Apply now!",
    provider_funding_body:
      "Bavarian State Ministry of Health, Care and Prevention",
    overview_allocated_budget: "",
    overview_program_acronym_id: "WoLeRaF, 43c-G8300-2022/7768-1",
    provider_additional_partners: "",
    overview_eligible_sectors_long:
      "Care and support, Health, Social services, Research and development in the care sector",
    overview_maximum_funding_amount: "100.000 €",
    overview_eligible_applicants_long:
      "Initiators of new outpatient-assisted shared living facilities in Bavaria, operators of full-time inpatient care facilities, operators of inpatient care facilities, and institutions suitable for scientifically supporting projects to improve framework conditions in care.",
    overview_program_title_without_acronym:
      "Funding for New Outpatient-Assisted Shared Living Facilities and Projects to Improve Quality of Life and Framework Conditions in Care",
    bookmarked: false,
  },
  {
    id: "ff76768f-84dc-446d-b8b0-8c6117161eeb",
    src_url:
      "https://www.foerderdatenbank.de/FDB/Content/DE/Foerderprogramm/Land/Berlin/foerderung-der-berufsausbildung-in-berlin.html",
    updated_at: "2025-06-14T06:54:13.859566+00:00",
    success: true,
    featured_priority: 0,
    overview_financial_instrument: "Grant",
    overview_award_channel: "DemandDrivenScheme",
    provider_program_level: "Regional",
    program_status: "Open",
    overview_eligible_applicants_short: [
      "Businesses",
      "EducationalandResearch",
      "NonProfit",
    ],
    overview_eligible_sectors_short: [
      "EducationAndVocationalTraining",
      "ResearchAndDevelopment",
      "Other",
    ],
    overview_target_stages_short: ["Implementation", "ExperimentalDevelopment"],
    overview_countries: ["Germany"],
    overview_single_consortium: "OptionalConsortium",
    overview_company_size: [],
    contact: {
      name: "Handwerkskammer Berlin",
      subtitle: "Abteilung IV/FBB",
      address: "Blücherstraße 68, 10961 Berlin",
      phone: "030 25903381",
      fax: "030 25903380",
      email: "fbb@hwk-Berlin.de",
      website: {
        url: "https://www.hwk-berlin.de/",
        name: "Handwerkskammer Berlin",
      },
    },
    funding_translations: [
      {
        id: "ff76768f-84dc-446d-b8b0-8c6117161eeb",
        title: "Vocational Training Promotion",
        success: true,
        language: "en",
        permalink: "berlin-vocational-training-promotion-grant",
        seo_title: "Berlin Training Funding: Secure Grants Up to €10,000",

        updated_at: "2025-06-14T06:54:13.859566+00:00",
        seo_keywords: [
          "Vocational Training Berlin",
          "Training Funding Berlin",
          "In-company Training Grant",
          "Funding Disadvantaged Youth",
          "Training Positions Berlin",
          "Chamber of Crafts Berlin Funding",
          "Model Trials Vocational Education",
          "Collaborative Training Berlin",
          "Funding Single Parents Training",
          "Women in Atypical Professions",
          "Refugee Training Berlin",
          "Training Remuneration Grant",
          "Pilot Projects Vocational Education",
        ],
        overview_region: "Berlin (Germany)",
        overview_deadline: "30.06.2025",
        introduction_short:
          "The State of Berlin supports companies in increasing the number and quality of in-company training positions. With this funding program, trainers can receive grants for various training forms, such as collaborative training or the promotion of specific target groups. The goal is to facilitate access to vocational training and support the securing of skilled workers in Berlin.",
        overview_open_until: "30.06.2025",
        provider_managed_by:
          "Berlin Chamber of Crafts, Senate Department for Labor, Social Affairs, Equality, Integration, Diversity and Anti-Discrimination",
        overview_beneficiary:
          "Businesses, Chambers of Crafts, eligible training providers and companies for creating and improving in-company training positions, and for supporting disadvantaged persons in initial training.",
        seo_meta_description:
          "Discover grants for businesses in Berlin to promote vocational training. Support is available for collaborative training, disadvantaged individuals, women in atypical professions, single parents, and refugees. Secure funding for your training positions now!",
        provider_funding_body:
          "Senate Department for Labor, Social Affairs, Equality, Integration, Diversity and Anti-Discrimination",
        overview_allocated_budget: "",
        overview_program_acronym_id: "",
        provider_additional_partners:
          "Federal Ministry of Education and Research (BMBF), Federal Ministry for Economic Affairs and Energy (BMWI), Heinz-Piest-Institute for Craft Technology, other professional institutes of the trade",
        overview_eligible_sectors_long:
          "Vocational training, crafts, agriculture, model trials and pilot projects in vocational education.",
        overview_maximum_funding_amount: "€10,000",
        overview_eligible_applicants_long:
          "Training companies based in Berlin, Berlin Chamber of Crafts and comparable institutions of other trades, eligible training providers and companies.",
        overview_program_title_without_acronym:
          "Promotion of Vocational Training in the State of Berlin 2021 to 2025",
      },
    ],
    bookmarks: [],
    title: "Vocational Training Promotion",
    language: "en",
    permalink: "berlin-vocational-training-promotion-grant",
    seo_title: "Berlin Training Funding: Secure Grants Up to €10,000",

    seo_keywords: [
      "Vocational Training Berlin",
      "Training Funding Berlin",
      "In-company Training Grant",
      "Funding Disadvantaged Youth",
      "Training Positions Berlin",
      "Chamber of Crafts Berlin Funding",
      "Model Trials Vocational Education",
      "Collaborative Training Berlin",
      "Funding Single Parents Training",
      "Women in Atypical Professions",
      "Refugee Training Berlin",
      "Training Remuneration Grant",
      "Pilot Projects Vocational Education",
    ],
    overview_region: "Berlin (Germany)",
    overview_deadline: "30.06.2025",
    introduction_short:
      "The State of Berlin supports companies in increasing the number and quality of in-company training positions. With this funding program, trainers can receive grants for various training forms, such as collaborative training or the promotion of specific target groups. The goal is to facilitate access to vocational training and support the securing of skilled workers in Berlin.",
    overview_open_until: "30.06.2025",
    provider_managed_by:
      "Berlin Chamber of Crafts, Senate Department for Labor, Social Affairs, Equality, Integration, Diversity and Anti-Discrimination",
    overview_beneficiary:
      "Businesses, Chambers of Crafts, eligible training providers and companies for creating and improving in-company training positions, and for supporting disadvantaged persons in initial training.",
    seo_meta_description:
      "Discover grants for businesses in Berlin to promote vocational training. Support is available for collaborative training, disadvantaged individuals, women in atypical professions, single parents, and refugees. Secure funding for your training positions now!",
    provider_funding_body:
      "Senate Department for Labor, Social Affairs, Equality, Integration, Diversity and Anti-Discrimination",
    overview_allocated_budget: "",
    overview_program_acronym_id: "",
    provider_additional_partners:
      "Federal Ministry of Education and Research (BMBF), Federal Ministry for Economic Affairs and Energy (BMWI), Heinz-Piest-Institute for Craft Technology, other professional institutes of the trade",
    overview_eligible_sectors_long:
      "Vocational training, crafts, agriculture, model trials and pilot projects in vocational education.",
    overview_maximum_funding_amount: "€10,000",
    overview_eligible_applicants_long:
      "Training companies based in Berlin, Berlin Chamber of Crafts and comparable institutions of other trades, eligible training providers and companies.",
    overview_program_title_without_acronym:
      "Promotion of Vocational Training in the State of Berlin 2021 to 2025",
    bookmarked: false,
  },
]
